name: Doxygen

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install doxygen
      run: sudo apt-get update && sudo apt-get install -y doxygen
    - name: run doxygen
      run: doxygen ./docs/libft
