name: submit

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: git user
      run: |
          git config user.name github-actions
          git config user.email tspoof@student.hive.fi
    - name: checkout
      run: git checkout -b vog master
    - name: stuff
      run: |
          git rm -r test .github/ ./docs ./test .gitignore README.md
    - name: commit & push
      run: |
          git commit -m "submit setup"
          git push --force origin vog
